baseURL                = "https://blog.catmoimoi.ccwu.cc/"
locale                 = "zh-cn"
title                  = "Catmoimoi"
theme                  = "hugo-theme-stack"
defaultContentLanguage = "zh"
hasCJKLanguage         = true

[pagination]
    pagerSize = 8

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"

[services.disqus]
    shortname = ""

[sitemap]
    changefreq = "weekly"
    filename   = "sitemap.xml"
    priority   = 0.5

[outputs]
    home = ["HTML", "RSS"]
